Added Matrix Exponentiation
keon/algorithms pull request #711
Opened 2020-10-02 12:28 UTC by c-utkarsh

2020-10-02 12:56 UTC, goswami-rahul requested changes

2020-10-02 12:56 UTC, goswami-rahul commented on algorithms/matrix/__init__.py
> +from .matrix_exponentiation import *
We don't need this. `multiply` collides with `multiply.py`.

2020-10-02 12:56 UTC, goswami-rahul commented on algorithms/matrix/matrix_exponentiation.py
> +    res0 = matrix_exponentiation(mat, 0)
Add tests at [`tests/test_matrix.py`](https://github.com/keon/algorithms/blob/master/tests/test_matrix.py) similar to other tests.

2020-10-02 16:53 UTC, c-utkarsh commented
Hi @goswami-rahul, I've incorporated the requested changes.

2020-10-04 12:12 UTC, goswami-rahul approved these changes
Thanks. LGTM

2020-10-04 12:12 UTC, merged