finding number of digits using logs created with unit tests
keon/algorithms pull request #740
Opened 2020-11-17 18:59 UTC by vicky1999

num_digits.py was created to find the number of digits in a number using log10 method in math module.
This PR was created from #659 

Implementation and unit tests were done.

2021-01-24 10:41 UTC, ankit167 requested changes

2021-01-24 10:41 UTC, ankit167 commented on algorithms/maths/num_digits.py
> +  if(n==0):
Please handle the case if n < 0

2021-01-24 10:41 UTC, ankit167 commented on tests/test_maths.py
> +        self.assertEqual(1,num_digits(8))
Add test case for:
1. n = 0
2. n < 0

2021-01-24 14:38 UTC, vicky1999 commented on tests/test_maths.py
> +        self.assertEqual(1,num_digits(8))
Sure.  I'll do that

2021-01-24 14:58 UTC, vicky1999 commented
the test case for n<0 has been handled and the unit tests were created for:
- n=0
- n<0

2021-01-25 11:26 UTC, ankit167 approved these changes

2021-01-27 13:02 UTC, merged